"""Generate the full project report as a Word (.docx) file, styled to match the
NIT Rourkela report template — expanded, illustrated and submission-grade.

Produces docs/Project_Report.docx for "Counterfeit Bank Currency Detection with
Various Machine Learning Techniques" by Sneha Shaw. The script:
  * draws clean, colored diagrams (workflow, architecture, DFD, activity, CNN,
    Random Forest, results bar-chart and confusion heatmap) with PIL,
  * renders real guilloche security-pattern art from the project's own backend,
  * embeds the NIT Rourkela logo on the title page and certificate,
  * lays out 12 chapters with detailed explanation, tables and code listings,
  * keeps References as the very last section.

Re-run to regenerate:  python scripts/build_report_doc.py
Open in Word/LibreOffice and press Ctrl+A then F9 to fill the contents fields.
"""

import importlib.util
import json
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor, Inches

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "Project_Report.docx"
LOGO = DOCS / "nit_logo.png"
GEN = DOCS / "_report_figs"
GEN.mkdir(exist_ok=True)
# Real app screenshots live here as committed files (NOT regenerated by this
# script), so embedding them from disk means a rebuild can never drop them.
SHOTS = DOCS / "screenshots"
SHOTS.mkdir(exist_ok=True)

# ----- front-matter facts -----
TITLE = "COUNTERFEIT BANK CURRENCY DETECTION WITH VARIOUS MACHINE LEARNING TECHNIQUES"
TITLE_TC = ("Counterfeit Bank Currency Detection with Various Machine Learning "
            "Techniques")
AUTHOR = "Sneha Shaw"
ROLL = "SIP25OF125"
SUPERVISOR = "Prof. Sanjeev Patel"
SUPERVISOR_DESIG = "Assistant Professor Grade-I"
DEPT = "Department of Computer Science and Engineering"
INSTITUTE_TC = "National Institute of Technology Rourkela"
DEGREE = "BACHELOR OF TECHNOLOGY"
BRANCH = "COMPUTER SCIENCE AND ENGINEERING"
SESSION = "2024–2025"
MONTH_YEAR = "JULY 2025"
PLACE_DATE = "July 2025"

# ----- colours -----
MUTED = RGBColor(0x60, 0x60, 0x60)
BLACK = RGBColor(0x00, 0x00, 0x00)
# Headings are plain black (per review feedback — no dark-blue headings).
HEADING = BLACK

C_TEAL = (31, 111, 107)
C_BLUE = (47, 84, 150)
C_LIGHT = (238, 244, 247)
C_LIGHT2 = (245, 242, 234)
C_TX = (33, 37, 41)
C_ARROW = (80, 88, 92)
C_SHADOW = (208, 214, 216)
C_GRIDMAX = (31, 111, 107)


# ===========================================================================
# PIL diagram helpers
# ===========================================================================

_FONT_CACHE = {}


def _font(size, bold=False):
    key = (size, bold)
    if key in _FONT_CACHE:
        return _FONT_CACHE[key]
    from PIL import ImageFont
    candidates = (["arialbd.ttf", "Arial Bold.ttf"] if bold
                  else ["arial.ttf", "Arial.ttf"])
    f = None
    for name in candidates:
        try:
            f = ImageFont.truetype(name, size)
            break
        except Exception:
            continue
    if f is None:
        f = ImageFont.load_default()
    _FONT_CACHE[key] = f
    return f


def _text_center(d, cx, y, text, font, fill):
    w = d.textlength(text, font=font)
    d.text((cx - w / 2, y), text, font=font, fill=fill)


def _box(d, x0, y0, x1, y1, header, items, header_color=C_TEAL, fill=C_LIGHT,
         hsize=30, isize=23, radius=18):
    # drop shadow
    d.rounded_rectangle([x0 + 7, y0 + 7, x1 + 7, y1 + 7], radius=radius,
                        fill=C_SHADOW)
    d.rounded_rectangle([x0, y0, x1, y1], radius=radius, fill=fill,
                        outline=header_color, width=3)
    cx = (x0 + x1) / 2
    hf = _font(hsize, True)
    _text_center(d, cx, y0 + 14, header, hf, header_color)
    if items:
        d.line([x0 + 18, y0 + 14 + hsize + 12, x1 - 18, y0 + 14 + hsize + 12],
               fill=header_color, width=2)
    iy = y0 + 14 + hsize + 22
    itf = _font(isize)
    for it in items:
        d.text((x0 + 30, iy), "•  " + it, font=itf, fill=C_TX)
        iy += isize + 11


def _arrow_down(d, cx, y0, y1, color=C_ARROW, width=4):
    d.line([cx, y0, cx, y1], fill=color, width=width)
    d.polygon([(cx - 9, y1 - 14), (cx + 9, y1 - 14), (cx, y1)], fill=color)


def _arrow_h(d, x0, x1, cy, color=C_ARROW, width=4):
    d.line([x0, cy, x1, cy], fill=color, width=width)
    d.polygon([(x1 - 14, cy - 9), (x1 - 14, cy + 9), (x1, cy)], fill=color)


def fig_vflow(path, steps, title=None, header_color=C_TEAL, start_end=False):
    """Vertical stack of boxes joined by down-arrows. steps: [(header,[items])]."""
    from PIL import Image, ImageDraw
    W = 1400
    margin = 90
    top = 50
    gap = 50
    line_h = 34
    bw = W - 2 * margin

    heights = [70 + len(items) * line_h + (16 if items else 0)
               for _, items in steps]
    circle = 60 if start_end else 0
    total = top + circle + sum(heights) + gap * (len(steps) - 1) + circle + top
    if start_end:
        total += gap * 2

    img = Image.new("RGB", (W, total), "white")
    d = ImageDraw.Draw(img)
    cx = W / 2
    y = top

    if start_end:
        d.ellipse([cx - 16, y, cx + 16, y + 32], fill=(40, 40, 40))
        y += 32
        _arrow_down(d, cx, y, y + gap)
        y += gap

    spans = []
    for header, items in steps:
        bh = 70 + len(items) * line_h + (16 if items else 0)
        _box(d, margin, y, margin + bw, y + bh, header, items,
             header_color=header_color)
        spans.append((y, y + bh))
        y += bh
        if (header, items) != steps[-1] or start_end:
            _arrow_down(d, cx, y, y + gap)
            y += gap

    if start_end:
        d.ellipse([cx - 18, y, cx + 18, y + 36], outline=(40, 40, 40), width=4)
        d.ellipse([cx - 9, y + 9, cx + 9, y + 27], fill=(40, 40, 40))
        y += 36

    img.crop((0, 0, W, min(total, y + top))).save(path)


def fig_architecture(path):
    from PIL import Image, ImageDraw
    W, H = 1480, 1180
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    cx = W / 2
    m = 90
    bw = W - 2 * m

    y = 50
    _box(d, m, y, m + bw, y + 110, "Frontend — Next.js + React + Tailwind",
         ["Upload / camera, verdict banner, panels, charts"])
    y2 = y + 110
    _arrow_down(d, cx, y2, y2 + 70)
    lbl = _font(20)
    d.text((cx + 18, y2 + 18), "REST API: /predict /explain /chat /security-pattern",
           font=lbl, fill=C_TX)
    y = y2 + 70
    _box(d, m, y, m + bw, y + 100, "FastAPI Backend (Uvicorn)",
         ["Validation, orchestration, response assembly"])
    y = y + 100
    _arrow_down(d, cx, y, y + 70)
    y = y + 70

    # three engines
    gapx = 40
    ew = (bw - 2 * gapx) / 3
    ey0 = y
    eh = 150
    engines = [
        ("MobileNetV2 CNN", ["Deep image", "classifier"], C_BLUE),
        ("Classical ML", ["SVM / RF /", "KNN / LogReg"], C_TEAL),
        ("Forensic Pipeline", ["14 visible-light", "checks"], (150, 80, 60)),
    ]
    centers = []
    for i, (hdr, items, col) in enumerate(engines):
        x0 = m + i * (ew + gapx)
        _box(d, x0, ey0, x0 + ew, ey0 + eh, hdr, items, header_color=col,
             hsize=26, isize=21)
        centers.append(x0 + ew / 2)
    y = ey0 + eh
    fy = y + 80
    for c in centers:
        _arrow_down(d, c, y, fy)
    _box(d, m, fy, m + bw, fy + 100,
         "Fusion + Hard Gates + Readability Gate",
         ["0.4 x CNN + 0.6 x forensic;  structure / colour / size veto"])
    y = fy + 100
    _arrow_down(d, cx, y, y + 70)
    y = y + 70
    _box(d, m, y, m + bw, y + 90, "Verdict",
         ["REAL  /  SUSPICIOUS  /  FAKE  /  UNVERIFIED"],
         header_color=(150, 80, 60))
    img.crop((0, 0, W, y + 90 + 50)).save(path)


def fig_cnn(path):
    from PIL import Image, ImageDraw
    W, H = 1560, 430
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    stages = ["Input\n224x224x3", "Conv\n+ ReLU", "Max\nPool", "Conv\n+ ReLU",
              "Max\nPool", "Fully\nConnected", "Sigmoid\nP(genuine)"]
    cols = [C_BLUE, C_TEAL, (120, 130, 140), C_TEAL, (120, 130, 140),
            C_BLUE, (150, 80, 60)]
    n = len(stages)
    m = 50
    gap = 36
    bw = (W - 2 * m - gap * (n - 1)) / n
    y0, y1 = 120, 300
    f = _font(24, True)
    for i, (s, col) in enumerate(zip(stages, cols)):
        x0 = m + i * (bw + gap)
        d.rounded_rectangle([x0 + 5, y0 + 5, x0 + bw + 5, y1 + 5], radius=12,
                            fill=C_SHADOW)
        d.rounded_rectangle([x0, y0, x0 + bw, y1], radius=12, fill=C_LIGHT,
                            outline=col, width=3)
        lines = s.split("\n")
        ty = (y0 + y1) / 2 - len(lines) * 15
        for ln in lines:
            _text_center(d, x0 + bw / 2, ty, ln, f, col)
            ty += 30
        if i < n - 1:
            ax = x0 + bw
            _arrow_h(d, ax, ax + gap, (y0 + y1) / 2)
    _text_center(d, W / 2, 40, "MobileNetV2 — convolution, pooling and "
                 "fully-connected layers", _font(28, True), C_TX)
    img.save(path)


def fig_random_forest(path):
    from PIL import Image, ImageDraw
    W, H = 1480, 880
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    cx = W / 2

    _box(d, cx - 320, 40, cx + 320, 150, "Feature vector (50-d)",
         ["LBP texture + colour + structure + forensic signals"])
    n = 4
    tw = 230
    span = W - 200
    xs = [120 + span * (i + 0.5) / n for i in range(n)]
    ty0, ty1 = 320, 470
    for i, tx in enumerate(xs):
        _arrow_down(d, cx, 150, 300) if i == 0 else None
        d.line([cx, 230, tx, ty0 - 14], fill=C_ARROW, width=3)
        d.polygon([(tx - 7, ty0 - 18), (tx + 7, ty0 - 18), (tx, ty0 - 4)],
                  fill=C_ARROW)
        d.polygon([(tx, ty0), (tx - tw / 2, ty1), (tx + tw / 2, ty1)],
                  fill=C_LIGHT, outline=C_TEAL)
        _text_center(d, tx, (ty0 + ty1) / 2 - 10, f"Tree {i + 1}",
                     _font(22, True), C_TEAL)
        _text_center(d, tx, ty1 + 12, "vote: R / F", _font(19), C_TX)

    agg_y = 600
    _box(d, cx - 300, agg_y, cx + 300, agg_y + 100,
         "Majority vote / probability", ["Average of the trees -> P(genuine)"])
    for tx in xs:
        d.line([tx, ty1 + 44, cx, agg_y - 14], fill=C_ARROW, width=3)
        d.polygon([(cx - 7, agg_y - 18), (cx + 7, agg_y - 18), (cx, agg_y - 4)],
                  fill=C_ARROW)
    vy = agg_y + 100
    _arrow_down(d, cx, vy, vy + 60)
    _box(d, cx - 220, vy + 60, cx + 220, vy + 150, "Verdict",
         ["REAL  /  FAKE  (+ confidence)"], header_color=(150, 80, 60))
    img.crop((0, 0, W, vy + 150 + 40)).save(path)


def fig_barchart(path):
    from PIL import Image, ImageDraw
    labels = ["SVM", "Random\nForest", "Logistic\nReg.", "KNN", "MobileNetV2\nCNN"]
    vals = [0.742, 0.742, 0.622, 0.514, 0.564]
    W, H = 1240, 720
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    ax0, ay0, ax1, ay1 = 130, 90, W - 70, H - 150
    d.line([ax0, ay0, ax0, ay1], fill=C_TX, width=3)
    d.line([ax0, ay1, ax1, ay1], fill=C_TX, width=3)
    ymax = 0.8
    for t in range(0, 9):
        v = t / 10
        gy = ay1 - (v / ymax) * (ay1 - ay0)
        d.line([ax0 - 8, gy, ax1, gy], fill=(225, 228, 230), width=1)
        d.text((ax0 - 70, gy - 12), f"{v:0.1f}", font=_font(20), fill=C_TX)
    n = len(vals)
    slot = (ax1 - ax0) / n
    bw = slot * 0.55
    for i, (lab, v) in enumerate(zip(labels, vals)):
        x0 = ax0 + slot * i + (slot - bw) / 2
        by = ay1 - (v / ymax) * (ay1 - ay0)
        col = C_TEAL if v >= 0.7 else C_BLUE
        d.rectangle([x0, by, x0 + bw, ay1], fill=col)
        _text_center(d, x0 + bw / 2, by - 30, f"{v:0.3f}", _font(22, True), C_TX)
        ly = ay1 + 14
        for ln in lab.split("\n"):
            _text_center(d, x0 + bw / 2, ly, ln, _font(20), C_TX)
            ly += 24
    _text_center(d, W / 2, 30, "Test macro-F1 by technique", _font(30, True),
                 C_TX)
    img.save(path)


def fig_confusion(path):
    from PIL import Image, ImageDraw
    matrix = [[31, 11, 0, 0], [10, 7, 5, 1]]
    cols = ["REAL", "SUSPICIOUS", "FAKE", "UNVERIFIED"]
    rows = ["Genuine", "Fake"]
    W, H = 1180, 560
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    gx0, gy0 = 230, 150
    cw, ch = 200, 130
    vmax = max(max(r) for r in matrix) or 1
    fhead = _font(24, True)
    fcell = _font(34, True)
    for j, c in enumerate(cols):
        _text_center(d, gx0 + cw * (j + 0.5), gy0 - 42, c, _font(21, True), C_TX)
    for i, r in enumerate(rows):
        d.text((40, gy0 + ch * (i + 0.5) - 16), r, font=fhead, fill=C_TX)
        for j in range(len(cols)):
            v = matrix[i][j]
            frac = v / vmax
            col = tuple(int(255 + (C_GRIDMAX[k] - 255) * frac) for k in range(3))
            x0 = gx0 + cw * j
            y0 = gy0 + ch * i
            d.rectangle([x0, y0, x0 + cw, y0 + ch], fill=col,
                        outline=(180, 185, 188), width=2)
            tx = (255, 255, 255) if frac > 0.5 else C_TX
            _text_center(d, x0 + cw / 2, y0 + ch / 2 - 22, str(v), fcell, tx)
    _text_center(d, gx0 + cw * 2, 40, "End-to-end verdict confusion matrix",
                 _font(28, True), C_TX)
    d.text((40, gy0 + ch * 2 + 30), "Rows = ground truth, columns = system "
           "verdict.", font=_font(20), fill=C_TX)
    img.save(path)


def _roc_fallback():
    """Operating-point ROC (one real test point per model) when the
    precomputed curves are unavailable. Derived from the saved confusion
    matrices; positive class = genuine."""
    labels = [("svm_rbf", "SVM (RBF)"), ("random_forest", "Random Forest"),
              ("logistic_regression", "Logistic Regression"), ("knn", "KNN")]
    out = []
    try:
        models = json.loads(
            (ROOT / "models" / "classical" / "metrics.json")
            .read_text(encoding="utf-8"))["models"]
    except Exception:
        models = {}
    for key, lab in labels:
        m = models.get(key)
        if not m:
            continue
        cm = m["confusion_matrix"]          # [[TN, FP], [FN, TP]]
        tpr = cm[1][1] / max(cm[1][0] + cm[1][1], 1)
        fpr = cm[0][1] / max(cm[0][0] + cm[0][1], 1)
        out.append({"label": lab, "fpr": [0.0, fpr, 1.0], "tpr": [0.0, tpr, 1.0],
                    "auc": round((tpr + (1 - fpr)) / 2, 4)})
    # CNN operating point (BENCHMARK.md: fake[3,3] / genuine[4,7]).
    out.append({"label": "MobileNetV2 (CNN)", "fpr": [0.0, 0.5, 1.0],
                "tpr": [0.0, 0.6364, 1.0], "auc": 0.5682})
    return out


def _roc_data():
    """Real ROC curves from scripts/compute_roc.py if present, else the
    operating-point fallback. Returns a list of {label, fpr, tpr, auc}."""
    p = GEN / "roc_data.json"
    if p.exists():
        try:
            curves = json.loads(p.read_text(encoding="utf-8"))["curves"]
            return [{"label": c["label"], "fpr": c["fpr"], "tpr": c["tpr"],
                     "auc": c["auc"]} for c in curves.values()]
        except Exception:
            pass
    return _roc_fallback()


def fig_roc(path):
    """ROC curve per ML technique, drawn from the real test-set probabilities
    computed by scripts/compute_roc.py. Best AUC is listed first."""
    from PIL import Image, ImageDraw
    items = sorted(_roc_data(), key=lambda c: -c["auc"])
    W, H = 1360, 980
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    ax0, ay0, ax1, ay1 = 150, 120, 860, 830
    gf = _font(20)

    def X(v):
        return ax0 + v * (ax1 - ax0)

    def Y(v):
        return ay1 - v * (ay1 - ay0)

    for t in range(0, 11, 2):
        v = t / 10
        d.line([X(v), ay0, X(v), ay1], fill=(232, 235, 237), width=1)
        d.line([ax0, Y(v), ax1, Y(v)], fill=(232, 235, 237), width=1)
        _text_center(d, X(v), ay1 + 14, f"{v:0.1f}", gf, C_TX)
        d.text((ax0 - 54, Y(v) - 12), f"{v:0.1f}", font=gf, fill=C_TX)

    # chance diagonal (dashed)
    steps = 44
    for i in range(0, steps, 2):
        t0, t1 = i / steps, (i + 1) / steps
        d.line([X(t0), Y(t0), X(t1), Y(t1)], fill=(176, 181, 184), width=2)
    d.line([ax0, ay0, ax0, ay1], fill=C_TX, width=3)
    d.line([ax0, ay1, ax1, ay1], fill=C_TX, width=3)

    palette = [C_BLUE, C_TEAL, (200, 120, 40), (150, 80, 60), (120, 120, 130)]
    for item, col in zip(items, palette):
        pts = [(X(fx), Y(ty)) for fx, ty in zip(item["fpr"], item["tpr"])]
        d.line(pts, fill=col, width=4, joint="curve")
        for px, py in pts:
            d.ellipse([px - 4, py - 4, px + 4, py + 4], fill=col)

    _text_center(d, (ax0 + ax1) / 2, ay1 + 52, "False Positive Rate",
                 _font(24, True), C_TX)
    ylab = Image.new("RGBA", (420, 44), (255, 255, 255, 0))
    _text_center(ImageDraw.Draw(ylab), 210, 6, "True Positive Rate",
                 _font(24, True), C_TX)
    ylab = ylab.rotate(90, expand=True)
    img.paste(ylab, (ax0 - 122, int((ay0 + ay1) / 2) - 210), ylab)
    _text_center(d, (ax0 + ax1) / 2, 50,
                 "ROC curves by machine-learning technique", _font(28, True), C_TX)

    lx, ly = ax1 + 40, ay0 + 30
    d.rounded_rectangle([lx - 18, ly - 22, W - 24, ly + len(items) * 52 + 4],
                        radius=14, fill=(250, 251, 252),
                        outline=(212, 216, 218), width=2)
    for item, col in zip(items, palette):
        d.line([lx, ly + 14, lx + 44, ly + 14], fill=col, width=6)
        d.ellipse([lx + 18, ly + 8, lx + 30, ly + 20], fill=col)
        d.text((lx + 58, ly), item["label"], font=_font(19, True), fill=C_TX)
        d.text((lx + 58, ly + 25), f"AUC = {item['auc']:0.2f}",
               font=_font(17), fill=C_ARROW)
        ly += 52
    img.save(path)


def _actor(d, cx, cy, name):
    d.ellipse([cx - 16, cy - 60, cx + 16, cy - 28], outline=C_TX, width=3)
    d.line([cx, cy - 28, cx, cy + 18], fill=C_TX, width=3)
    d.line([cx - 26, cy - 12, cx + 26, cy - 12], fill=C_TX, width=3)
    d.line([cx, cy + 18, cx - 22, cy + 56], fill=C_TX, width=3)
    d.line([cx, cy + 18, cx + 22, cy + 56], fill=C_TX, width=3)
    _text_center(d, cx, cy + 64, name, _font(22, True), C_TX)


def fig_usecase(path):
    from PIL import Image, ImageDraw
    W, H = 1500, 1040
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    bx0, by0, bx1, by1 = 370, 60, 1130, 980
    d.rounded_rectangle([bx0, by0, bx1, by1], radius=22, outline=C_BLUE, width=3)
    _text_center(d, (bx0 + bx1) / 2, by0 + 16,
                 "Counterfeit Currency Detection System", _font(24, True), C_BLUE)
    cases = [
        "Upload banknote image",
        "Capture from camera",
        "Analyse note (CNN + ML + forensic)",
        "View verdict & confidence",
        "View plain-language explanation",
        "Listen / switch to Hindi",
        "Generate security pattern",
        "Ask the help chatbot",
    ]
    ex = (bx0 + bx1) / 2
    n = len(cases)
    top, bot = by0 + 80, by1 - 50
    ys = [top + (bot - top) * (i + 0.5) / n for i in range(n)]
    ell_w, ell_h = 380, 58
    for cy, label in zip(ys, cases):
        d.ellipse([ex - ell_w / 2, cy - ell_h / 2, ex + ell_w / 2, cy + ell_h / 2],
                  fill=C_LIGHT, outline=C_TEAL, width=2)
        _text_center(d, ex, cy - 11, label, _font(19), C_TX)
    user_x, user_y = 150, H / 2 - 40
    sys_x, sys_y = W - 130, H / 2 - 40
    _actor(d, user_x, user_y, "User")
    _actor(d, sys_x, sys_y, "System")
    for cy in ys:
        d.line([user_x + 28, user_y - 6, ex - ell_w / 2, cy], fill=C_ARROW, width=2)
    for idx in (2, 4, 6, 7):       # cases the System actor fulfils
        d.line([ex + ell_w / 2, ys[idx], sys_x - 28, sys_y - 6],
               fill=C_ARROW, width=2)
    img.save(path)


def fig_sequence(path):
    from PIL import Image, ImageDraw
    W, H = 1580, 980
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    actors = ["User", "Web UI\n(Next.js)", "FastAPI\nBackend",
              "CNN / Classical /\nForensic engines", "Fusion +\nHard gates"]
    n = len(actors)
    m = 70
    span = W - 2 * m
    xs = [m + span * (i + 0.5) / n for i in range(n)]
    head_y0, head_y1 = 50, 132
    life_bottom = H - 50
    hf = _font(19, True)
    for x, name in zip(xs, actors):
        bw = 250
        d.rounded_rectangle([x - bw / 2, head_y0, x + bw / 2, head_y1],
                            radius=12, fill=C_LIGHT, outline=C_BLUE, width=2)
        lines = name.split("\n")
        ty = (head_y0 + head_y1) / 2 - len(lines) * 12
        for ln in lines:
            _text_center(d, x, ty, ln, hf, C_TX)
            ty += 24
        yy = head_y1
        while yy < life_bottom:
            d.line([x, yy, x, min(yy + 12, life_bottom)],
                   fill=(176, 181, 184), width=2)
            yy += 22
    msgs = [
        (0, 1, "capture / upload photo"),
        (1, 2, "POST /predict (image)"),
        (2, 3, "run CNN + classical + forensic"),
        (3, 2, "scores + per-check evidence"),
        (2, 4, "combine  0.4·CNN + 0.6·forensic"),
        (4, 2, "apply hard gates -> verdict"),
        (2, 1, "JSON: verdict + evidence"),
        (1, 0, "show verdict & explanation"),
    ]
    y = head_y1 + 66
    mf = _font(17)
    for a, b, label in msgs:
        xa, xb = xs[a], xs[b]
        d.line([xa, y, xb, y], fill=C_ARROW, width=3)
        if xb >= xa:
            d.polygon([(xb - 14, y - 8), (xb - 14, y + 8), (xb, y)], fill=C_ARROW)
        else:
            d.polygon([(xb + 14, y - 8), (xb + 14, y + 8), (xb, y)], fill=C_ARROW)
        _text_center(d, (xa + xb) / 2, y - 26, label, mf, C_TX)
        y += 92
    img.save(path)


def make_guilloche(seed, out, size=720):
    spec = importlib.util.spec_from_file_location(
        "security_pattern", ROOT / "backend" / "security_pattern.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    out.write_bytes(mod.pattern_png(seed, size))


# ===========================================================================
# docx helpers
# ===========================================================================

def _field(run, instr, placeholder=""):
    begin = OxmlElement("w:fldChar"); begin.set(qn("w:fldCharType"), "begin")
    itext = OxmlElement("w:instrText"); itext.set(qn("xml:space"), "preserve")
    itext.text = instr
    sep = OxmlElement("w:fldChar"); sep.set(qn("w:fldCharType"), "separate")
    holder = OxmlElement("w:t"); holder.text = placeholder
    end = OxmlElement("w:fldChar"); end.set(qn("w:fldCharType"), "end")
    for el in (begin, itext, sep, holder, end):
        run._r.append(el)


def set_pgnum(section, fmt, start=1):
    sectPr = section._sectPr
    for el in sectPr.findall(qn("w:pgNumType")):
        sectPr.remove(el)
    pg = OxmlElement("w:pgNumType")
    pg.set(qn("w:fmt"), fmt)
    pg.set(qn("w:start"), str(start))
    sectPr.append(pg)


def footer_pagenum(section):
    section.footer.is_linked_to_previous = False
    p = section.footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.text = ""
    _field(p.add_run(), "PAGE", "")


def _shade(paragraph, fill="F4F5F7"):
    pPr = paragraph._p.get_or_add_pPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), fill)
    pPr.append(shd)


def page_break(doc):
    doc.add_page_break()


def ctext(doc, text, size=12, bold=False, italic=False, color=None, after=6,
          before=0):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_after = Pt(after)
    p.paragraph_format.space_before = Pt(before)
    p.paragraph_format.line_spacing = 1.0
    r = p.add_run(text)
    r.bold = bold
    r.italic = italic
    r.font.size = Pt(size)
    if color:
        r.font.color.rgb = color
    return p


def h1(doc, text):
    p = doc.add_heading(text, level=1)
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    return p


def h2(doc, text):
    return doc.add_heading(text, level=2)


def h3(doc, text):
    return doc.add_heading(text, level=3)


def body(doc, text, after=10):
    p = doc.add_paragraph(text)
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    p.paragraph_format.space_after = Pt(after)
    return p


def bullet(doc, text):
    return doc.add_paragraph(text, style="List Bullet")


def numbered(doc, text):
    return doc.add_paragraph(text, style="List Number")


def chapter(doc, title):
    page_break(doc)
    return h1(doc, title)


def caption(doc, text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(text)
    r.italic = True
    r.font.size = Pt(10.5)
    p.paragraph_format.space_after = Pt(12)


def table_caption(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = True
    r.font.size = Pt(10.5)
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.space_before = Pt(6)


def add_image(doc, path, width_inches, cap=None):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(8)
    try:
        p.add_run().add_picture(str(path), width=Inches(width_inches))
    except Exception:
        p.add_run(f"[ image unavailable: {Path(path).name} ]").italic = True
    if cap:
        caption(doc, cap)


def figure_placeholder(doc, label, cap):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(8)
    r = p.add_run(f"[ {label} — insert image here ]")
    r.italic = True
    r.font.color.rgb = MUTED
    caption(doc, f"{label}: {cap}")


def screenshot(doc, fname, label, cap, width=6.1):
    """Embed a real app screenshot from docs/screenshots/<fname> if it exists,
    otherwise a placeholder naming the exact file to drop in. Because the image
    is loaded from a committed file (not pasted into Word by hand), it is
    re-embedded on every rebuild and can never be lost again."""
    path = SHOTS / fname
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(8)
    if path.exists():
        try:
            p.add_run().add_picture(str(path), width=Inches(width))
        except Exception:
            r = p.add_run(f"[ {label}: could not read docs/screenshots/{fname} ]")
            r.italic = True
            r.font.color.rgb = MUTED
    else:
        r = p.add_run(f"[ {label} — drop the screenshot at "
                      f"docs/screenshots/{fname} ]")
        r.italic = True
        r.font.color.rgb = MUTED
    caption(doc, f"{label}: {cap}")


def table(doc, headers, rows):
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Table Grid"
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for i, htext in enumerate(headers):
        run = t.rows[0].cells[i].paragraphs[0].add_run(htext)
        run.bold = True
    for row in rows:
        cells = t.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = str(val)
    doc.add_paragraph().paragraph_format.space_after = Pt(6)
    return t


def code_block(doc, source_path, max_lines=400):
    try:
        text = source_path.read_text(encoding="utf-8")
    except Exception:
        body(doc, f"(source unavailable: {source_path.name})")
        return
    lines = text.splitlines()
    truncated = len(lines) > max_lines
    for line in lines[:max_lines]:
        p = doc.add_paragraph()
        pf = p.paragraph_format
        pf.space_after = Pt(0)
        pf.space_before = Pt(0)
        pf.line_spacing = 1.0
        _shade(p)
        r = p.add_run(line if line else " ")
        r.font.name = "Consolas"
        r.font.size = Pt(9)
    if truncated:
        body(doc, f"... (listing shortened to {max_lines} lines; the full "
                  f"{len(lines)}-line source is in {source_path.name}).")


# ===========================================================================
# front matter
# ===========================================================================

def cover(doc):
    doc.add_paragraph()
    ctext(doc, TITLE, size=17, bold=True, after=22)
    ctext(doc, "Project Report submitted in partial fulfillment of", after=14)
    ctext(doc, DEGREE, size=13, bold=True, after=2)
    ctext(doc, "IN", after=2)
    ctext(doc, BRANCH, size=13, bold=True, after=18)
    ctext(doc, "By", after=2)
    ctext(doc, AUTHOR.upper(), size=13, bold=True, after=2)
    ctext(doc, f"Roll Number: {ROLL}", after=18)
    ctext(doc, "Based on research carried out under the supervision of", after=2)
    ctext(doc, SUPERVISOR, size=13, bold=True, after=10)
    if LOGO.exists():
        add_image(doc, LOGO, 1.4)
    ctext(doc, MONTH_YEAR, size=13, bold=True, after=18, before=8)
    ctext(doc, "Department of Computer Science and Engineering", after=2)
    ctext(doc, INSTITUTE_TC.upper(), size=13, bold=True, after=2)


def certificate(doc):
    if LOGO.exists():
        add_image(doc, LOGO, 0.95)
    ctext(doc, "Department of Computer Science and Engineering", after=2,
          before=4)
    ctext(doc, INSTITUTE_TC, bold=True, after=18)
    p = doc.add_paragraph()
    p.add_run(SUPERVISOR).bold = True
    doc.add_paragraph(SUPERVISOR_DESIG)
    pd = doc.add_paragraph()
    pd.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    pd.add_run(PLACE_DATE)
    ctext(doc, "Supervisor’s Certificate", size=15, bold=True, after=18,
          before=14)
    body(doc,
         f"This is to certify that the work presented in this report entitled "
         f"“{TITLE_TC}” submitted by {AUTHOR}, Roll Number: {ROLL}, is "
         f"a record of original project work carried out by the candidate under "
         f"my supervision and guidance. The study was conducted in the {DEPT} "
         f"during the academic session {SESSION}, in partial fulfillment of the "
         f"requirements of the Summer Internship Project of the BTech degree in "
         f"Computer Science and Engineering.")
    for _ in range(4):
        doc.add_paragraph()
    pr = doc.add_paragraph()
    pr.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    pr.add_run(SUPERVISOR)


def declaration(doc):
    page_break(doc)
    ctext(doc, "Declaration of Originality", size=15, bold=True, after=18,
          before=4)
    body(doc,
         f"I, {AUTHOR}, {ROLL}, hereby declare that this project report entitled "
         f"“{TITLE_TC}” presents my work carried out under the "
         f"supervision of {SUPERVISOR} in the {DEPT}, {INSTITUTE_TC}, and to the "
         f"best of my knowledge, contains no material previously published or "
         f"written by another person, nor any material presented by me for the "
         f"award of any degree or diploma at any institution. Wherever the work "
         f"of others has been used, it has been duly acknowledged and "
         f"referenced.")
    for _ in range(4):
        doc.add_paragraph()
    pr = doc.add_paragraph()
    pr.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    pr.add_run(AUTHOR)
    doc.add_paragraph(PLACE_DATE)
    doc.add_paragraph(INSTITUTE_TC)


def dedication(doc):
    page_break(doc)
    ctext(doc, "DEDICATION", size=15, bold=True, after=18, before=4)
    body(doc,
         f"I dedicate this report to my supervisor {SUPERVISOR}, whose guidance "
         f"and mentorship have been invaluable throughout this project. This "
         f"work is a token of my deepest appreciation for the support and "
         f"knowledge imparted to me during my time at {INSTITUTE_TC}, which has "
         f"significantly contributed to my growth and learning.")
    body(doc,
         "I also dedicate this work to my beloved parents, whose unconditional "
         "love, support and encouragement have been my constant source of "
         "strength throughout this journey.")
    body(doc,
         "Lastly, this work is dedicated to everyone working to make financial "
         "systems safer and more accessible, and to the citizens for whom an "
         "honest, easy-to-use counterfeit-detection tool can make a real "
         "difference.")


def abstract(doc):
    page_break(doc)
    ctext(doc, "ABSTRACT", size=15, bold=True, after=18, before=4)
    body(doc,
         "Counterfeit currency is a persistent threat to the economy; the "
         "Reserve Bank of India reports continued detection of fake high-value "
         "notes. For an ordinary person it is very difficult to tell a forged "
         "note from a genuine one, because modern fakes reproduce many visible "
         "features with high precision. This project presents an automated, "
         "explainable system that takes a phone photograph of an Indian Rupee "
         "banknote and returns a single, defensible verdict — REAL, "
         "SUSPICIOUS, FAKE, or UNVERIFIED (“cannot verify — "
         "retake”).")
    body(doc,
         "Rather than relying on a single model, the system fuses three "
         "independent views. A deep-learning image classifier (MobileNetV2 "
         "convolutional neural network) scores the whole note. Various classical "
         "machine-learning techniques — Support Vector Machine, Random "
         "Forest, K-Nearest Neighbours and Logistic Regression — are "
         "trained on a hand-crafted fifty-dimensional feature vector (Local "
         "Binary Pattern texture, colour distribution, structural descriptors "
         "and OCR-free forensic signals) and benchmarked against one another. An "
         "explainable forensic pipeline of fourteen visible-light security "
         "checks (serial number, denomination, watermark, security thread, "
         "ascending-serial typography, micro-lettering, colour palette, note "
         "proportions, bleed lines and the identification mark) each returns "
         "PASS, FAIL or INFO with the measured numbers shown.")
    body(doc,
         "On a held-out test split the classical techniques (best: SVM / Random "
         "Forest at about 0.74 macro-F1) outperform the off-the-shelf CNN (about "
         "0.56), showing that engineered features are more sample-efficient on a "
         "small dataset. End-to-end, the fused system never misclassifies a "
         "genuine note as fake (0% false positives) and flags the majority of "
         "fakes, with an honestly-stated accuracy ceiling driven by "
         "training-data volume rather than method. Beyond classification, the "
         "system provides a plain-language explanation layer, an accessibility "
         "(read-aloud and Hindi) mode, a help chatbot and a generative "
         "anti-copy security-pattern studio, all of which run locally with "
         "offline fallbacks. The result is a trustworthy, understandable and "
         "practical screening aid for Indian banknotes.")


def contents(doc):
    page_break(doc)
    h1(doc, "TABLE OF CONTENTS")
    p = doc.add_paragraph()
    _field(p.add_run(), 'TOC \\o "1-2" \\h \\z \\u',
           "Select all (Ctrl+A) and press F9 in Word to build this table.")

    page_break(doc)
    h1(doc, "LIST OF FIGURES")
    figs = [
        ("5.1", "MobileNetV2 CNN layer pipeline"),
        ("5.2", "Random Forest ensemble (trees voting)"),
        ("6.1", "System architecture"),
        ("6.2", "Data Flow Diagram"),
        ("6.3", "Activity Diagram"),
        ("6.4", "Use Case Diagram"),
        ("6.5", "Sequence Diagram"),
        ("7.1", "Overall detection workflow"),
        ("9.1", "Generated guilloche pattern (seed ABHI-500-2026)"),
        ("9.2", "Generated guilloche pattern (seed ABHI-500-2029)"),
        ("10.1", "Test macro-F1 by technique"),
        ("10.2", "ROC curves by machine-learning technique"),
        ("10.3", "End-to-end verdict confusion matrix"),
    ]
    table(doc, ["Figure", "Title"], [[a, b] for a, b in figs])

    h1(doc, "LIST OF TABLES")
    tabs = [
        ("4.1", "Hardware requirements"),
        ("4.2", "Software requirements"),
        ("5.1", "Feature-vector composition"),
        ("8.1", "Forensic security-feature checks"),
        ("10.1", "Technique comparison (held-out test)"),
        ("10.2", "End-to-end verdict confusion matrix"),
    ]
    table(doc, ["Table", "Title"], [[a, b] for a, b in tabs])


# ===========================================================================
# chapters
# ===========================================================================

def chapters(doc, figs):
    # --- 1 Introduction ---
    h1(doc, "CHAPTER 1: INTRODUCTION")
    h2(doc, "1.1 Background")
    body(doc,
         "Counterfeiting is the unlawful reproduction of genuine currency. In "
         "India the sole authority to issue banknotes is the Reserve Bank of "
         "India (RBI), and every year a quantity of counterfeit notes enters "
         "circulation. After the 2016 demonetisation the ₹500 and "
         "₹2000 denominations became the principal targets for forgery, so "
         "the ability to screen these notes quickly is valuable to ordinary "
         "citizens, shopkeepers and small businesses.")
    body(doc,
         "Dedicated fake-note detector machines exist, but they are mostly "
         "available only inside banks and are not reachable by a common person "
         "at the moment a note is received. There is therefore a clear need for "
         "an accessible software solution that can judge a note from nothing "
         "more than a photograph taken on a mobile phone.")
    body(doc,
         "This project applies digital image processing and various "
         "machine-learning techniques to the visible features of Indian "
         "banknotes. The captured image is processed to extract security "
         "features — the serial number, the watermark region, the security "
         "thread, the colour palette, the note proportions, micro-lettering, "
         "bleed lines and the identification mark — and these signals, "
         "together with deep and classical machine-learning classifiers, are "
         "fused into a single verdict. Importantly, the system is honest: where "
         "a feature cannot be measured from the photograph it reports INFO "
         "rather than fabricating a pass or a fail. In line with the reference "
         "literature, only visible-light image processing is used; ultraviolet "
         "behaviour is approximated as an information-only proxy and never "
         "drives the verdict, because genuine UV verification requires "
         "dedicated hardware.")
    h2(doc, "1.2 Problem Statement")
    body(doc,
         "By visual inspection alone it is very difficult for a human being to "
         "distinguish a forged note from a genuine one, because many features of "
         "a modern fake closely resemble the original. Discriminating between "
         "fake and genuine currency is therefore a challenging task. Existing "
         "automated systems often rely on a single technique, depend on "
         "specialised hardware or controlled scans, and present a bare result "
         "without explaining it or admitting the cases they cannot decide. This "
         "project addresses the need for an automated, low-cost and explainable "
         "system that predicts, from an ordinary photograph, whether a banknote "
         "is genuine or counterfeit, while remaining honest about uncertainty.")
    h2(doc, "1.3 Motivation")
    body(doc,
         "Counterfeit currency reduces the value of genuine money and harms the "
         "economy, while ordinary citizens have little access to reliable "
         "verification tools. With smartphones now ubiquitous, a phone-photo "
         "based detector can bring screening to everyone. Machine learning makes "
         "it possible to combine many individually-weak visual signals into a "
         "dependable decision, and to compare several techniques to find the "
         "most reliable. Equally motivating is trustworthiness: the system "
         "should explain its verdict in plain language, support visually-"
         "impaired and bilingual users, and above all never reject genuine "
         "money — because wrongly rejecting a real note is the most "
         "damaging error in practice.")
    h2(doc, "1.4 Objectives")
    for t in [
        "To detect counterfeit Indian banknotes from a single phone photograph "
        "using image processing and machine learning.",
        "To implement and compare various machine-learning techniques (CNN, "
        "SVM, Random Forest, KNN, Logistic Regression) on the same task and "
        "report an honest benchmark.",
        "To implement each security feature named in the brief as a real, "
        "measured check that returns PASS, FAIL or INFO.",
        "To fuse the models and forensic checks into one verdict that minimises "
        "false positives (never rejecting genuine money).",
        "To make the result trustworthy and usable through plain-language "
        "explanation, accessibility and a help assistant.",
    ]:
        numbered(doc, t)
    h2(doc, "1.5 Contribution")
    body(doc, "The core contributions of this project are:")
    for t in [
        "A complete, modular machine-learning pipeline — from data "
        "ingestion and note localisation, through feature extraction and "
        "training, to evaluation and a live web application.",
        "A comparison of multiple ML techniques (deep CNN versus classical "
        "SVM / Random Forest / KNN / Logistic Regression) on a single, "
        "reproducible benchmark.",
        "A forensic layer in which every security feature is a real measurement "
        "returning PASS / FAIL / INFO — never a hardcoded result.",
        "A fused verdict with hard gates that achieves a 0% false-positive rate "
        "on the evaluation set.",
        "An explanation, accessibility and help layer (plain-language "
        "summaries, read-aloud, Hindi, help chatbot and a generative "
        "security-pattern studio) that runs locally with offline fallbacks.",
    ]:
        bullet(doc, t)
    h2(doc, "1.6 Outline")
    body(doc,
         "Chapter 2 reviews related work. Chapter 3 analyses the existing and "
         "proposed systems. Chapter 4 lists the system requirements. Chapter 5 "
         "describes the machine-learning techniques in detail. Chapter 6 "
         "presents the system design and UML models. Chapter 7 covers the "
         "methodology and implementation. Chapter 8 details the forensic "
         "security-feature checks. Chapter 9 describes the explainability, "
         "accessibility and generative features. Chapter 10 reports the results "
         "and discussion. Chapter 11 covers system testing, and Chapter 12 "
         "concludes with future scope.")

    # --- 2 Literature Survey ---
    chapter(doc, "CHAPTER 2: LITERATURE SURVEY")
    body(doc,
         "A literature survey was carried out to understand existing approaches "
         "to fake-currency detection, the features they rely on, and the "
         "machine-learning techniques applied. The reviewed works span classical "
         "image-processing pipelines, statistical classifiers and deep learning. "
         "Before building any system it is important to study the time, data and "
         "method requirements of prior work, and to identify where they fall "
         "short — which directly motivated the design choices of this "
         "project.")
    h2(doc, "2.1 Image Processing and ML in Currency Detection")
    body(doc,
         "Image-processing methods extract security regions — the security "
         "thread, watermark, identification mark and micro-lettering — and "
         "compare them against a genuine reference. Statistical and ensemble "
         "classifiers then decide authenticity from the extracted features, "
         "while deep convolutional networks learn features directly from the "
         "note image. A recurring theme is that the choice of feature, and the "
         "quality and quantity of data, matter more than the specific "
         "classifier.")
    h2(doc, "2.2 Survey of Representative Works")
    lit = [
        ("A. A. Mandankandy and K. E. Kannammal, “Fake currency detection: "
         "a survey,” Gedrag en Organisatie, 33(4), 2020.",
         "Surveys segmentation, feature extraction and classification, and notes "
         "that classifiers improve reliability over direct region comparison "
         "alone."),
        ("S. Arya and M. Sasikumar, “Fake currency detection,” "
         "ICRAECC, 2020.",
         "Detects fakes by counting interruptions in the security thread and "
         "using image entropy, implemented in MATLAB."),
        ("A. Singh, K. Bhoyar, A. Pandey, P. Mankani and A. Tekriwal, "
         "“Detection of fake currency using image processing,” IJERT "
         "8(12), 2019.",
         "Proposes a mobile, image-based approach with cloud storage for "
         "portability and accuracy."),
        ("T. Kumar, T. Subhash and D. Regan, “Fake-currency recognition "
         "system for Indian notes using image-processing techniques,” 2019.",
         "Fuses security-thread, intaglio (RBI logo) and identification-mark "
         "scores; reports a low mean-square error of about 1%."),
        ("A. Upadhyaya, V. Shokeen and G. Srivastava, “Analysis of "
         "counterfeit-currency detection techniques for a classification "
         "model,” 2018.",
         "Compares Logistic Regression with Linear Discriminant Analysis and "
         "finds Logistic Regression more accurate for currency authentication."),
        ("M. Laavanya and V. Vijayaraghavan, “Real-time fake-currency note "
         "detection using deep learning,” IJEAT 9(1S5), 2019.",
         "Uses a transfer-learned CNN trained on ₹50/200/500/2000 notes to "
         "identify forgeries in real time."),
        ("A. Vidhate, Y. Shah, R. Biyani, H. Keshri and R. Nikhare, "
         "“Fake-currency detection application,” IRJET 08(05), 2021.",
         "Proposes an application using image processing and CNN classifiers, "
         "comparing the input against a prototype."),
        ("T. Agasti, G. Burand, P. Wade and P. Chitra, “Fake-currency "
         "detection using image processing,” ICSET-2017.",
         "Extracts multiple features of Indian notes in MATLAB and predicts "
         "whether the note is fake."),
    ]
    for ref, summary in lit:
        p = doc.add_paragraph(style="List Number")
        p.add_run(ref).bold = True
        body(doc, summary)
    h2(doc, "2.3 Reference Works and Identified Gaps")
    body(doc,
         "Two works directly shaped this project's scope: an IEEE paper "
         "combining Teachable-Machine classification with MATLAB edge/feature "
         "extraction, and a B.E. thesis using a CNN together with Local Binary "
         "Pattern (LBP) region comparison. Both rely on visible-light processing "
         "only. Accordingly this project adopts LBP-based features for its "
         "classical techniques and treats UV as an honest proxy.")
    body(doc,
         "A common limitation of prior work is the use of a single technique, "
         "default parameters, and results reported without explanation or "
         "uncertainty handling. Few studies compare several algorithms on one "
         "benchmark or admit when a feature cannot be measured. This project "
         "closes these gaps by (a) comparing deep and classical techniques on a "
         "single reproducible benchmark, (b) implementing every check to return "
         "PASS / FAIL / INFO honestly, (c) fusing the views with hard gates to "
         "prevent false positives, and (d) adding explanation and accessibility "
         "so the result is interpretable to an ordinary user.")

    # --- 3 System Analysis ---
    chapter(doc, "CHAPTER 3: SYSTEM ANALYSIS")
    h2(doc, "3.1 Existing System")
    body(doc,
         "Existing approaches recognise paper currency using digital "
         "image-processing techniques, selecting around eight characteristics of "
         "Indian notes — identification mark, optically variable ink, "
         "see-through register, colour code, security thread, watermark, latent "
         "image and micro-lettering. Features are extracted from the note image "
         "and compared with those of a genuine reference. Most existing systems, "
         "however, rely on a single technique, often depend on specialised "
         "hardware or controlled scans, and present results as bare numbers "
         "without explaining the verdict or admitting when a feature cannot be "
         "measured.")
    h2(doc, "3.2 Proposed System")
    body(doc,
         "The proposed system identifies whether a given banknote is fake from "
         "an ordinary photograph. It improves on existing work in four ways. "
         "First, it compares several machine-learning techniques rather than "
         "relying on one. Second, it implements every security feature as a real "
         "measurement that returns PASS, FAIL or INFO, never a hardcoded result. "
         "Third, it fuses the models and checks with hard gates so the overall "
         "system is safer than any single model — most importantly achieving "
         "a 0% false-positive rate. Fourth, it adds an explanation, "
         "accessibility and help layer that makes the result trustworthy and "
         "understandable. The whole system runs locally and returns a fast, "
         "honest result.")
    h2(doc, "3.3 Feasibility Study")
    body(doc,
         "Technical feasibility — the system is built from mature, "
         "open-source libraries (OpenCV, scikit-learn, TensorFlow, EasyOCR, "
         "FastAPI, Next.js) and runs on a standard CPU, so no special hardware "
         "is required. Economic feasibility — all components are free and "
         "open source, and the application runs locally, so deployment cost is "
         "negligible. Operational feasibility — the user only needs to take "
         "a photograph; the plain-language output and help chatbot make the "
         "system usable by non-experts.")
    h2(doc, "3.4 Functional Requirements")
    for t in [
        "Accept a banknote image by file upload or live camera capture.",
        "Locate and crop the note, then run the CNN, classical model and "
        "forensic checks.",
        "Return a single verdict (REAL / SUSPICIOUS / FAKE / UNVERIFIED) with "
        "per-feature evidence and a confidence value.",
        "Provide a plain-language explanation and manual verification steps.",
        "Expose the result in English and Hindi, with read-aloud support.",
    ]:
        bullet(doc, t)
    h2(doc, "3.5 Non-Functional Requirements")
    for t in [
        "Reliability — never crash on bad input; degrade gracefully and "
        "never raise to the user.",
        "Honesty — report INFO when a feature cannot be measured rather "
        "than guessing.",
        "Performance — return a verdict within a few seconds on a CPU.",
        "Privacy — process images locally; do not store or transmit them.",
        "Usability — clear, plain-language interface accessible to "
        "non-experts.",
    ]:
        bullet(doc, t)

    # --- 4 System Requirements ---
    chapter(doc, "CHAPTER 4: SYSTEM REQUIREMENTS")
    h2(doc, "4.1 Hardware Requirements")
    table_caption(doc, "Table 4.1: Hardware requirements.")
    table(doc, ["Component", "Specification"],
          [["Processor", "Intel Core i3 or higher (CPU-only is sufficient)"],
           ["RAM", "4 GB minimum (8 GB recommended)"],
           ["Storage", "~2 GB free (code, model weights, dataset)"],
           ["Camera", "Any phone/webcam for live capture (optional)"],
           ["Display", "Standard monitor"]])
    h2(doc, "4.2 Software Requirements")
    table_caption(doc, "Table 4.2: Software requirements.")
    table(doc, ["Component", "Specification"],
          [["Operating System", "Windows 10 / 11 (also Linux / macOS)"],
           ["Backend language", "Python 3.11"],
           ["Backend framework", "FastAPI + Uvicorn"],
           ["Computer vision", "OpenCV"],
           ["OCR", "EasyOCR (primary), Tesseract (fallback)"],
           ["Deep learning", "TensorFlow / Keras (MobileNetV2)"],
           ["Classical ML", "scikit-learn, joblib, scikit-image"],
           ["Generative AI", "Anthropic Claude (with offline fallback)"],
           ["Frontend", "Next.js + React + Tailwind CSS"]])
    h2(doc, "4.3 Technology Specification")
    body(doc,
         "Python is a general-purpose, interpreted, object-oriented, high-level "
         "language with a clear syntax and a rich scientific-computing ecosystem, "
         "which makes it well suited to this project. The backend uses FastAPI, "
         "a high-performance Python web framework, to expose the prediction, "
         "explanation, chat and security-pattern endpoints. OpenCV provides the "
         "image-processing primitives for the forensic checks, EasyOCR reads the "
         "serial number and denomination, TensorFlow/Keras runs the MobileNetV2 "
         "classifier, and scikit-learn trains the classical models. The frontend "
         "is built with Next.js and React for an interactive, modern user "
         "interface.")

    # --- 5 Machine Learning Techniques ---
    chapter(doc, "CHAPTER 5: MACHINE LEARNING TECHNIQUES")
    body(doc,
         "The project is named for its use of various machine-learning "
         "techniques. Three complementary families of models are used so that "
         "their agreement — or disagreement — can be shown honestly: a "
         "deep convolutional neural network, a set of classical statistical "
         "classifiers, and a rule-based forensic layer (Chapter 8). This chapter "
         "describes the learning techniques and how a photograph flows through "
         "each of them.")
    h2(doc, "5.1 Convolutional Neural Network (MobileNetV2)")
    body(doc,
         "A Convolutional Neural Network (CNN) learns image features "
         "automatically through a stack of layers. Convolution layers slide "
         "small learnable filters over the image to produce feature maps that "
         "capture edges, textures and patterns; pooling layers downsample these "
         "maps to keep the strongest signal while reducing size; and fully "
         "connected layers at the end combine everything into a final score. "
         "This project uses MobileNetV2 — an efficient CNN designed for "
         "low-compute devices — with a 224×224 input and a sigmoid output "
         "that gives the probability the note is genuine. The whole cropped "
         "banknote photo is fed to the network, which decides REAL/FAKE from the "
         "raw pixels. MobileNetV2 was chosen for its speed on an ordinary CPU; "
         "however, as reported in Chapter 10, the off-the-shelf CNN is the "
         "weakest single component on this small dataset (deep networks need "
         "thousands of images), so it is weighted below the forensic score in "
         "the final fusion.")
    add_image(doc, figs["cnn"], 6.3,
              "Figure 5.1: MobileNetV2 — convolution, pooling and "
              "fully-connected layers turn the note image into P(genuine).")
    h2(doc, "5.2 Hand-crafted Feature Vector")
    body(doc,
         "The classical techniques do not look at raw pixels. Instead, each "
         "located note is summarised into a fixed list of fifty numbers — "
         "the feature vector — by backend/features.py. This is how a "
         "photograph is turned into something a classical model can read: the "
         "cropped note is converted into texture, colour and structural "
         "statistics, so two photos of the same note (different lighting or "
         "angle) map to similar vectors. The fifty numbers are grouped as shown "
         "in Table 5.1.")
    table_caption(doc, "Table 5.1: Composition of the 50-dimensional feature "
                       "vector.")
    table(doc, ["Group", "Dim", "Description"],
          [["LBP histogram", "26", "Uniform Local Binary Pattern (radius 3, 24 "
            "points) texture histogram."],
           ["Hue histogram", "12", "Coarse hue distribution of coloured pixels."],
           ["Colour scalars", "5", "Mean/std saturation, mean/std value, hue "
            "entropy."],
           ["Structure", "4", "Aspect ratio, edge density, gray mean, gray std."],
           ["Forensic signals", "3", "Micro-print sharpness, watermark variance, "
            "vertical-thread energy."]])
    body(doc,
         "The vector is deterministic (the same image always yields the same "
         "numbers) and is standardised by a StandardScaler that is fit on the "
         "training split only and persisted with the model, so there is no "
         "difference between training and live prediction.")
    h2(doc, "5.3 Classical Techniques Compared")
    body(doc,
         "Four classical supervised techniques are trained on the same "
         "fifty-dimensional vectors and compared:")
    bullet(doc, "Support Vector Machine (SVM, RBF kernel) — finds the "
                "boundary that separates genuine from fake vectors with the "
                "widest possible margin; the RBF kernel lets that boundary be "
                "curved rather than a straight line.")
    bullet(doc, "Random Forest — an ensemble of many decision trees whose "
                "votes are combined; it is the live second opinion in the "
                "application and is detailed in Section 5.4.")
    bullet(doc, "K-Nearest Neighbours (KNN) — classifies a new note by the "
                "majority label of the most similar training vectors.")
    bullet(doc, "Logistic Regression — a simple, interpretable linear "
                "baseline that outputs a genuine/fake probability.")
    body(doc,
         "All four are trained with group-aware cross-validation (a note's "
         "augmented copies never split across folds) and the best technique by "
         "cross-validation is selected without ever looking at the test set.")
    h2(doc, "5.4 Random Forest — Detailed View")
    body(doc,
         "Random Forest is the classical technique chosen as the live second "
         "opinion in the running application, so it is described here in detail.")
    body(doc,
         "A single decision tree splits the data by asking a sequence of "
         "yes/no questions about the feature values (for example, “is the "
         "LBP texture energy above a threshold?”, “is the colour "
         "saturation low?”) until it reaches a leaf that says genuine or "
         "fake. One tree on its own tends to overfit — it memorises the "
         "training notes and generalises poorly. Random Forest fixes this by "
         "building many trees (an ensemble) and combining them. Two sources of "
         "randomness keep the trees diverse:")
    bullet(doc, "Bagging (bootstrap sampling) — each tree is trained on a "
                "different random sample of the training notes, drawn with "
                "replacement.")
    bullet(doc, "Feature subsampling — at each split a tree may only choose "
                "from a random subset of the fifty features, so different trees "
                "rely on different evidence.")
    body(doc,
         "To classify a new note, every tree votes genuine or fake and the "
         "forest averages the votes into a probability of genuine. Averaging "
         "many de-correlated trees cancels their individual mistakes, making "
         "Random Forest robust, resistant to overfitting and effective even on a "
         "small dataset — exactly the conditions of this project. It also "
         "exposes a feature-importance ranking, showing which of the fifty "
         "features most influence the decision.")
    add_image(doc, figs["rf"], 6.0,
              "Figure 5.2: Random Forest — the feature vector is shown to "
              "many decision trees whose votes are averaged into a verdict.")
    body(doc, "How a photograph is processed by Random Forest in this system "
              "(implemented in backend/classical.py):")
    for t in [
        "The user supplies a banknote photo; the note is located and cropped "
        "from the background.",
        "backend/features.py converts the cropped note into the fifty-number "
        "feature vector (texture, colour, structure and forensic signals).",
        "The saved StandardScaler scales the vector to the range the forest was "
        "trained on.",
        "The scaled vector is passed to the trained Random Forest, whose trees "
        "vote; predict_proba returns the probability that the note is genuine.",
        "That probability becomes the Random Forest verdict (REAL if ≥ 0.5, "
        "else FAKE) with a confidence, shown as an independent second opinion.",
    ]:
        numbered(doc, t)
    body(doc,
         "Random Forest was selected as the live model because it was the best "
         "classical technique by cross-validation and, on the held-out test "
         "split, tied for the best test macro-F1 (0.742) while catching the most "
         "fakes (Chapter 10). The verdict logic keeps it as a transparent second "
         "opinion rather than the sole decider, so its agreement or disagreement "
         "with the CNN and the forensic score is always visible to the user.")
    h2(doc, "5.5 Fusion into One Verdict")
    body(doc,
         "The deep model, the best classical model and the forensic score are "
         "fused by a calibrated rule (score = 0.4×CNN + 0.6×forensic). "
         "The forensic component is weighted higher because the CNN is brittle "
         "on out-of-distribution inputs. Three hard gates — structural "
         "sanity, colour palette and note proportions — can veto a REAL "
         "verdict regardless of score. When the photograph is too unclear to "
         "read the note, the system returns UNVERIFIED instead of guessing.")

    # --- 6 System Design ---
    chapter(doc, "CHAPTER 6: SYSTEM DESIGN")
    h2(doc, "6.1 System Architecture")
    body(doc,
         "The application is a FastAPI backend with a Next.js frontend. A photo "
         "posted to the /predict endpoint is decoded and the note auto-located; "
         "three engines then run on it — the MobileNetV2 CNN, the best "
         "classical model as a second opinion, and the forensic pipeline. Their "
         "outputs are fused, subjected to the hard gates and a readability gate, "
         "and returned to the UI, which renders every check. Figure 6.1 shows "
         "the component architecture.")
    add_image(doc, figs["arch"], 6.3, "Figure 6.1: System architecture.")
    h2(doc, "6.2 Data Flow Diagram")
    body(doc,
         "The Data Flow Diagram (DFD) shows how information moves through the "
         "system, from the input image to the final verdict, and the "
         "transformations applied at each stage.")
    add_image(doc, figs["dfd"], 5.2, "Figure 6.2: Data Flow Diagram.")
    h2(doc, "6.3 UML Diagrams")
    body(doc,
         "The Unified Modeling Language (UML) is a standard language for "
         "specifying, visualising and documenting software systems. The activity "
         "diagram (Figure 6.3) shows the overall flow of control from capture to "
         "verdict; the use-case diagram (Figure 6.4) shows the interactions "
         "between the user, the system and its functions; and the sequence "
         "diagram (Figure 6.5) shows the order of messages exchanged during a "
         "prediction.")
    add_image(doc, figs["activity"], 4.4, "Figure 6.3: Activity Diagram.")
    add_image(doc, figs["usecase"], 5.7,
              "Figure 6.4: Use Case Diagram — the User uploads or captures a "
              "note and views the verdict, explanation, pattern and chatbot, "
              "while the System actor fulfils the analysis and generative cases.")
    add_image(doc, figs["sequence"], 6.4,
              "Figure 6.5: Sequence Diagram — the order of messages exchanged "
              "during a prediction, from the User through the Web UI and Backend "
              "to the CNN/classical/forensic engines, fusion and verdict.")

    # --- 7 Methodology and Implementation ---
    chapter(doc, "CHAPTER 7: METHODOLOGY AND IMPLEMENTATION")
    h2(doc, "7.1 Overall Workflow")
    body(doc,
         "Figure 7.1 summarises the end-to-end workflow: a banknote photo is "
         "captured, pre-processed, passed through the ML models and forensic "
         "checks, fused into a verdict, and finally evaluated.")
    add_image(doc, figs["workflow"], 5.4,
              "Figure 7.1: Overall detection workflow.")
    h2(doc, "7.2 Dataset")
    body(doc,
         "The dataset comprises 65 labelled full-note images (42 genuine / 23 "
         "fake): 34 project fixtures (clean scans, phone photos and synthetic "
         "degradations) plus 31 images from the public, Apache-2.0 Kaggle "
         "“Fake Currency Detection Dataset” (19 real and 12 photographs "
         "of real fake notes). The images are organised under dataset/real and "
         "dataset/fake and indexed deterministically into a label-stratified "
         "train/test split. The dataset is deliberately small and the report is "
         "honest about the resulting accuracy ceiling.")
    h2(doc, "7.3 Pre-processing")
    for t in [
        "Note localisation — a two-stage detector (Canny/contour and "
        "rotated-rectangle, with a GrabCut + saliency fallback for handheld, "
        "tilted or busy-background photos) crops the note.",
        "Denoising and grayscale conversion of the located note.",
        "Canonical resize so texture and colour features are "
        "resolution-comparable; small crops are upscaled before OCR.",
        "Feature scaling with StandardScaler (zero mean, unit variance), fit on "
        "the training split only.",
        "Group-aware train/test split with a fixed random seed so augmented "
        "copies of a note never leak across the split.",
    ]:
        bullet(doc, t)
    h2(doc, "7.4 Training Pipeline")
    body(doc,
         "Training is fully scripted and reproducible. build_dataset.py indexes "
         "the images; train_classical.py extracts features, augments the "
         "training set, and trains the SVM, Random Forest, KNN and Logistic "
         "Regression models with group-aware cross-validation, saving the best "
         "model and its scaler; benchmark_models.py produces the comparison "
         "table; and evaluate_system.py runs the full end-to-end verdict over "
         "the corpus. Re-running these scripts after adding more images "
         "automatically improves the system with no code change.")
    h2(doc, "7.5 Modules")
    for name, desc in [
        ("Data collection", "Indexes and labels the banknote images into a "
         "deterministic train/test split."),
        ("Pre-processing", "Locates and crops the note, denoises, converts to "
         "grayscale and resizes."),
        ("Feature extraction", "Builds the 50-d feature vector and measures each "
         "forensic security region."),
        ("Classification & fusion", "Runs the CNN and best classical model and "
         "fuses them with the forensic score under hard gates."),
        ("Explanation & assistant", "Generates plain-language explanations, the "
         "security-pattern art, and the help chatbot responses."),
    ]:
        p = doc.add_paragraph(style="List Bullet")
        p.add_run(name + " — ").bold = True
        p.add_run(desc)

    # --- 8 Forensic checks ---
    chapter(doc, "CHAPTER 8: FORENSIC SECURITY-FEATURE CHECKS")
    body(doc,
         "Alongside the machine-learning models, the system runs a pipeline of "
         "fourteen visible-light forensic checks. Each measures one security "
         "feature and returns PASS, FAIL or INFO with the measured number; INFO "
         "means the feature could not be assessed and is never counted as a "
         "fake pass or fail. This honesty is central to the project: a "
         "phone-photo miscount is treated as a resolution problem, not proof of "
         "forgery. Table 8.1 lists the checks.")
    table_caption(doc, "Table 8.1: Forensic security-feature checks.")
    table(doc, ["Check", "What it measures"],
          [["Structural sanity", "Aspect, edges, brightness, dark quadrants "
            "(hard gate)."],
           ["Serial number (OCR)", "Reads the serial via EasyOCR."],
           ["Serial typography", "Digit heights increase left-to-right on "
            "genuine notes."],
           ["Denomination", "EasyOCR digit voting + colour-palette tiebreak."],
           ["Proportion analysis", "Measured aspect vs canonical RBI mm "
            "dimensions."],
           ["Security thread", "Morphological vertical-feature detector."],
           ["Watermark", "Gandhi-panel gradient variance."],
           ["Gandhi portrait", "Haar-based portrait detection."],
           ["Micro-lettering", "Fine-print sharpness (never a false PASS)."],
           ["Bleed lines", "Counts edge lines vs RBI per-denomination count."],
           ["Identification mark", "Tactile-shape presence + touch guidance."],
           ["Colour palette", "Hue entropy + saturation (hard gate)."],
           ["UV (proxy)", "Visible-light approximation, INFO-only."],
           ["Digital tamper (ELA)", "Error-Level Analysis for edited images "
            "(INFO-only)."]])
    body(doc,
         "Several checks implement features named directly in the project brief. "
         "The serial-typography check is the brief's “the note number "
         "varies with size” feature: on genuine notes the serial digits "
         "grow in height from left to right, and the check fits a line through "
         "the digit heights to detect a flat (suspicious) serial. The colour "
         "palette check is the “colour variation” feature, and the "
         "bleed-line and identification-mark checks support the visually-"
         "impaired by reporting the tactile shape a genuine note should carry.")

    # --- 9 Beyond detection ---
    chapter(doc, "CHAPTER 9: EXPLAINABILITY, ACCESSIBILITY AND GENERATIVE FEATURES")
    body(doc,
         "The system is built to be trustworthy and usable, not merely a "
         "classifier. This chapter describes the features that surround the core "
         "detection. Every feature that can call an external AI service also has "
         "a deterministic offline fallback, so the entire product runs locally "
         "with no internet or API key.")
    h2(doc, "9.1 Plain-Language Explanation")
    body(doc,
         "The “Explain with AI” feature turns the technical result into "
         "a short, calm, plain-language summary plus the manual checks a person "
         "can perform by hand (tilt for the colour-shift, hold to light for the "
         "watermark, feel the raised print). It is accessibility-first: the text "
         "can be read aloud and is available in English and Hindi. When an API "
         "key is present it is produced by a large language model with a "
         "JSON-constrained response; otherwise a deterministic template built "
         "from the same forensic results is used, so the feature always works.")
    h2(doc, "9.2 Accessibility — Listen and Hindi")
    body(doc,
         "A “Listen” button reads the verdict and explanation aloud using "
         "the browser's speech synthesis, and an English/Hindi toggle localises "
         "both the verdict and the explanation. These features serve the "
         "visually-impaired and bilingual users that the reference papers "
         "highlight, and align with the tactile identification-mark check.")
    h2(doc, "9.3 Security Pattern Studio (Generative Anti-Copy Art)")
    body(doc,
         "What genuinely resists copying in real currency, on the design side, "
         "is guilloche — the fine, interwoven mathematical line-work that is "
         "easy to regenerate from a formula but very hard to reproduce by hand "
         "or through a scan-and-print cycle. The Security Pattern Studio "
         "procedurally generates such guilloche art from a seed: woven rings, a "
         "micro-text ring and a layered rosette. The generation is fully "
         "deterministic — the same seed always produces the same pattern, "
         "so a design keyed to a serial number can be regenerated and compared. "
         "Figures 9.1 and 9.2 show two patterns generated by the project's own "
         "backend for two seeds; note that different seeds yield completely "
         "different patterns, while the same seed always reproduces exactly. "
         "Crucially, the studio produces abstract ornament only — never "
         "banknote imagery — so it is the honest, legal interpretation of a "
         "“generative anti-copy” feature.")
    add_image(doc, figs["guilloche1"], 2.9,
              "Figure 9.1: Generated guilloche pattern for seed ABHI-500-2026.")
    add_image(doc, figs["guilloche2"], 2.9,
              "Figure 9.2: Generated guilloche pattern for seed ABHI-500-2029.")
    h2(doc, "9.4 Help Chatbot")
    body(doc,
         "A floating assistant answers questions about how the system works, "
         "what each verdict means, and how to run it. It is grounded in a "
         "curated knowledge base about this project, uses a large language model "
         "when available and a keyword-FAQ matcher offline, and refuses any "
         "request to make or pass off counterfeit money.")
    h2(doc, "9.5 Other Product Features")
    for t in [
        "Detected-note overlay — draws the located note region on the "
        "uploaded photo.",
        "Live camera capture — analyse a note straight from the webcam or "
        "phone camera through a framing guide.",
        "Grad-CAM heatmap — an attention overlay showing where the CNN "
        "looked.",
        "Downloadable PDF report — a print-ready one-page verdict summary.",
        "Digital-tamper (ELA) check — flags possibly edited images, "
        "informational only.",
    ]:
        bullet(doc, t)

    # --- 10 Results ---
    chapter(doc, "CHAPTER 10: RESULTS AND DISCUSSION")
    h2(doc, "10.1 Dataset and Metrics")
    body(doc,
         "Evaluation uses the 65-image labelled corpus, split into 48 training "
         "and 17 test images (augmentation applied only to the training split). "
         "Because counterfeiting is a two-class decision (genuine vs fake), this "
         "is a classification task and is evaluated with classification metrics "
         "— accuracy, precision, recall and the macro-averaged F1 score "
         "— together with the confusion matrix and, as the priority metric, "
         "the false-positive rate (how often a genuine note is wrongly called "
         "fake; target: zero).")
    h2(doc, "10.2 Technique Comparison")
    table_caption(doc, "Table 10.1: Technique comparison on the held-out test "
                       "split (1 = genuine, 0 = fake).")
    table(doc, ["Technique", "Test Acc", "Test macro-F1", "Fakes caught"],
          [["SVM (RBF)", "0.765", "0.742", "4/6"],
           ["Random Forest", "0.765", "0.742", "4/6"],
           ["Logistic Regression", "0.706", "0.622", "2/6"],
           ["KNN", "0.529", "0.514", "3/6"],
           ["MobileNetV2 (CNN)", "0.588", "0.564", "3/6"]])
    add_image(doc, figs["bar"], 5.5,
              "Figure 10.1: Test macro-F1 by technique.")
    body(doc,
         "The classical models trained on engineered features clearly outperform "
         "the off-the-shelf CNN, which collapses toward predicting “all "
         "genuine” on so little data. Random Forest, the best technique by "
         "cross-validation, runs as the live second opinion.")
    body(doc,
         "Figure 10.2 plots the Receiver Operating Characteristic (ROC) curve of "
         "each technique, computed from the real probability each trained model "
         "assigns to “genuine” on the held-out test images. A ROC curve "
         "traces the true-positive rate against the false-positive rate as the "
         "decision threshold is swept from 0 to 1, and the area under the curve "
         "(AUC) summarises how reliably a model ranks a genuine note above a fake "
         "one (0.5 = chance, 1.0 = perfect). Because the test split is only "
         "seventeen images, the curves are stepped and higher-variance — the "
         "same honesty caveat that applies to every test-set metric in this "
         "report.")
    add_image(doc, figs["roc"], 6.4,
              "Figure 10.2: ROC curves by technique on the held-out test split "
              "(positive class = genuine; dashed diagonal = chance).")
    body(doc,
         "AUC measures ranking quality and need not agree with the macro-F1 "
         "scores of Table 10.1, which are read at a single 0.5 threshold. SVM "
         "(RBF) ranks genuine notes above fakes most reliably (AUC ≈ 0.82); "
         "Random Forest — selected as the live second opinion by "
         "cross-validation — matches SVM's threshold decisions in Table 10.1 "
         "but ranks less cleanly on these seventeen images (AUC ≈ 0.64). The "
         "MobileNetV2 CNN lies on the chance diagonal (AUC ≈ 0.50), the "
         "clearest possible confirmation that, with so few images, the deep "
         "model fails to separate the two classes — exactly why it is "
         "weighted below the forensic score in the fused verdict.")
    h2(doc, "10.3 Whole-System End-to-End")
    table_caption(doc, "Table 10.2: End-to-end verdict confusion matrix (all 65 "
                       "images).")
    table(doc,
          ["Ground truth \\ Verdict", "REAL", "SUSPICIOUS", "FAKE", "UNVERIFIED"],
          [["Genuine", "31", "11", "0", "0"],
           ["Fake", "10", "7", "5", "1"]])
    add_image(doc, figs["confusion"], 5.0,
              "Figure 10.3: End-to-end verdict confusion matrix.")
    for t in [
        "0% false positives — a genuine note is never called FAKE. This "
        "priority property held across every change.",
        "74% of genuine notes cleared as REAL (the rest flagged SUSPICIOUS for "
        "review).",
        "About 57% of fakes flagged; the remainder (high-quality physical "
        "fakes) pass as REAL — the data-bound false-negative case.",
    ]:
        bullet(doc, t)
    h2(doc, "10.4 Negative Results (Reported Honestly)")
    for t in [
        "Re-training the CNN on 65 images scored 0.550 macro-F1 — worse "
        "than the kept model (0.564); CNNs need far more data.",
        "ORB motif/emblem matching false-failed genuine notes and was removed "
        "rather than shipped.",
        "Micro-print sharpness does not separate genuine from sharp fakes, so it "
        "only flags clearly-degraded print and never emits a false PASS.",
    ]:
        bullet(doc, t)
    body(doc,
         "Together these confirm a single conclusion: the binding constraint is "
         "training-data volume and the scarcity of real physical-counterfeit "
         "images, not the method.")
    h2(doc, "10.5 Discussion")
    body(doc,
         "The classical models win because hand-crafted features are "
         "sample-efficient on a small dataset, whereas a CNN needs thousands of "
         "images to generalise. The ensemble plus forensic hard gates make the "
         "system safer than any single model — notably the 0% false-positive "
         "rate, which matters most because rejecting genuine money is the worst "
         "error. Throughout, when a signal cannot be measured the system returns "
         "INFO rather than guessing, so it never manufactures confidence.")

    # --- 11 Testing ---
    chapter(doc, "CHAPTER 11: SYSTEM TESTING")
    body(doc,
         "Testing ensures that each component behaves correctly and that the "
         "system as a whole produces dependable results.")
    h2(doc, "11.1 Black-Box and White-Box Testing")
    body(doc,
         "Black-box (functional) testing checks the output produced for a given "
         "input and was used to verify the /predict, /explain, /chat and "
         "/security-pattern endpoints. White-box (structural) testing exercises "
         "the internal logic and was used for the deterministic helpers — "
         "feature extraction, readability assessment and pattern generation.")
    h2(doc, "11.2 Types of Testing Applied")
    for t in [
        "Unit testing — individual functions (feature-vector shape and "
        "determinism, verdict logic, pattern determinism).",
        "System testing — the full request/response flow across "
        "environments.",
        "Usability testing — the clarity and ease of use of the interface.",
        "Acceptance testing — that the delivered system meets the stated "
        "objectives.",
        "Regression testing — re-running the suite after each change, "
        "notably preserving the 0% false-positive property.",
    ]:
        bullet(doc, t)
    body(doc,
         "The implementation is covered by an automated test suite of more than "
         "130 tests (pytest) across the OCR, localisation, proportion, forensic, "
         "API, feature, fusion, explanation, pattern and chatbot modules, "
         "together with a manifest-driven fixture set and a diagnostic harness "
         "that reports objective confusion-matrix numbers.")

    # --- 12 Conclusion ---
    chapter(doc, "CHAPTER 12: CONCLUSION AND FUTURE WORK")
    h2(doc, "12.1 Conclusion")
    body(doc,
         "This project built an automated, explainable system that detects "
         "counterfeit Indian banknotes from a phone photograph using various "
         "machine-learning techniques. By fusing a deep CNN, several classical "
         "classifiers and an explainable forensic pipeline, the system delivers "
         "a fast, honest verdict and never rejects a genuine note (0% false "
         "positives) on the evaluation set. The comparison of techniques shows "
         "that, on a small dataset, classical models with engineered features "
         "outperform an off-the-shelf CNN. Beyond classification, the system is "
         "made trustworthy and usable through plain-language explanation, "
         "accessibility, a help chatbot and a generative anti-copy "
         "security-pattern studio, all running locally.")
    h2(doc, "12.2 Future Scope")
    body(doc,
         "In the future this work can be extended in several directions. The "
         "most impactful is to gather more labelled images, prioritising real "
         "physical counterfeits; the pipeline auto-improves on re-run with no "
         "code change. The REAL/SUSPICIOUS/FAKE thresholds can be recalibrated "
         "from ROC curves once the dataset is larger, reducing over-cautious "
         "SUSPICIOUS flags. The CNN and a learned fusion meta-classifier can be "
         "re-attempted when data supports it. Optional UV-reactive checks could "
         "be added if UV-lamp imagery becomes available, and the tool could be "
         "packaged as an installable mobile application for wider real-world "
         "use.")

    return lit


def appendices(doc):
    chapter(doc, "APPENDIX A: SCREENSHOTS")
    body(doc,
         "This appendix collects screenshots of the running application. The "
         "images are loaded from docs/screenshots/ when the report is built, so "
         "they are preserved automatically on every regeneration of this "
         "document.")
    shots = [
        ("01_home_upload.png", "Figure A.1",
         "Home / upload screen with the English–Hindi toggle."),
        ("02_verdict_genuine.png", "Figure A.2",
         "Verdict for a genuine ₹100 note (REAL) with the detected-note "
         "overlay and a 93.55% confidence."),
        ("03_what_we_checked.png", "Figure A.3",
         "“What we checked” — the plain-language security-feature "
         "summary (✓ looks right · ✗ a problem · — couldn't check)."),
        ("04_explain_ai.png", "Figure A.4",
         "“Explain with AI” — the plain-language explanation and the "
         "manual by-hand checks."),
        ("05_ml_comparison.png", "Figure A.5",
         "Technical details — the ML technique comparison (MobileNetV2 CNN "
         "and the Random Forest second opinion)."),
        ("06_forensic_analysis.png", "Figure A.6",
         "Forensic analysis — the proportion check and the grid of "
         "per-feature security checks."),
        ("07_serial_typography.png", "Figure A.7",
         "RBI serial-typography check — the serial digits ascending in "
         "size from left to right, as on genuine notes."),
        ("08_pattern_and_chatbot.png", "Figure A.8",
         "Security Pattern Studio (procedurally generated guilloche art) "
         "with the Help chatbot open."),
    ]
    for fname, label, cap in shots:
        screenshot(doc, fname, label, cap)

    chapter(doc, "APPENDIX B: SOURCE CODE")
    body(doc,
         "Representative modules are listed below, each preceded by a short "
         "explanation of what it does. The complete source resides in the "
         "project repository.")
    modules = [
        ("B.1 Feature extraction — backend/features.py",
         ROOT / "backend" / "features.py", 240,
         "Turns a banknote image into the fifty-number feature vector used by "
         "all classical models — the uniform Local Binary Pattern texture "
         "histogram, a hue/colour distribution, structural descriptors and three "
         "OCR-free forensic signals, concatenated into one fixed-length, "
         "deterministic vector. Using a single function guarantees that training "
         "and live prediction extract features identically."),
        ("B.2 Classical second opinion — backend/classical.py",
         ROOT / "backend" / "classical.py", 120,
         "Loads the best classical model (chosen by cross-validation — here "
         "Random Forest) and its saved scaler and scores an image. "
         "predict_classical extracts the feature vector, scales it, and calls "
         "predict_proba to obtain the probability that the note is genuine, "
         "returning a REAL/FAKE verdict with confidence. It never raises: if the "
         "model files are missing it returns an “unavailable” result. "
         "This is the code path described in Section 5.4."),
        ("B.3 GenAI explanation — backend/genai.py",
         ROOT / "backend" / "genai.py", 200,
         "Converts the verdict and forensic results into a plain-language "
         "explanation plus manual verification steps, in English or Hindi. With "
         "an API key it uses a large language model with a JSON-constrained "
         "response; otherwise it falls back to a deterministic template, so the "
         "feature always works offline. It never generates currency — only "
         "explains authenticity."),
        ("B.4 Generative security pattern — backend/security_pattern.py",
         ROOT / "backend" / "security_pattern.py", 270,
         "Procedurally generates the guilloche anti-copy art shown in Figures "
         "9.1 and 9.2 from a seed — woven rings, a micro-text ring and a "
         "layered rosette. The same seed always produces the same pattern, and "
         "it outputs abstract ornament only, never banknote imagery."),
        ("B.5 Help chatbot — backend/chatbot.py",
         ROOT / "backend" / "chatbot.py", 150,
         "Answers questions about the project. It is grounded in a curated "
         "knowledge base, uses a large language model when available and a "
         "keyword-FAQ matcher offline, and refuses any request related to making "
         "counterfeit money."),
        ("B.6 Grad-CAM attention — backend/gradcam.py",
         ROOT / "backend" / "gradcam.py", 80,
         "Computes a Grad-CAM heatmap that highlights where the MobileNetV2 "
         "model focused when scoring a note — an explainability view of the "
         "deep model."),
        ("B.7 API and orchestration — backend/main.py",
         ROOT / "backend" / "main.py", 160,
         "The FastAPI application: it validates uploads, runs the three engines, "
         "fuses their outputs under the hard gates and readability gate, and "
         "exposes the /predict, /diagnose, /explain, /chat and /security-pattern "
         "endpoints."),
        ("B.8 Forensic pipeline (excerpt) — backend/forensic.py",
         ROOT / "backend" / "forensic.py", 120,
         "The largest module; it implements note localisation and the fourteen "
         "security-feature checks. Only the opening section is reproduced here; "
         "the full module is in the repository."),
        ("B.9 Dataset indexing — scripts/build_dataset.py",
         ROOT / "scripts" / "build_dataset.py", 120,
         "Recursively ingests the images under dataset/, infers labels from the "
         "folder layout, validates them and writes a deterministic train/test "
         "index."),
        ("B.10 Classical training — scripts/train_classical.py",
         ROOT / "scripts" / "train_classical.py", 140,
         "Extracts features, augments the training set, trains the SVM, Random "
         "Forest, KNN and Logistic Regression models with group-aware "
         "cross-validation, and saves the best model and its scaler."),
    ]
    for title_, path, cap_lines, expl in modules:
        h2(doc, title_)
        body(doc, expl)
        code_block(doc, path, max_lines=cap_lines)


def references(doc, lit):
    chapter(doc, "REFERENCES")
    lit_refs = [r for r, _ in lit]
    idea_data_refs = [
        "Reserve Bank of India, “Know Your Banknotes — security "
        "features of Indian Rupee notes (Mahatma Gandhi New Series),” RBI, "
        "https://www.rbi.org.in.",
        "Kaggle, “Fake Currency Detection Dataset” (Apache-2.0 "
        "licence), https://www.kaggle.com.",
        "Mendeley Data, “Indian Currency Notes” image datasets, "
        "https://data.mendeley.com.",
        "Reference IEEE conference paper on fake-currency detection using "
        "Teachable-Machine classification with MATLAB edge/feature extraction.",
        "Reference B.E. thesis on fake-currency detection using a CNN with "
        "Local Binary Pattern (LBP) region comparison.",
    ]
    method_tool_refs = [
        "M. Sandler, A. Howard, M. Zhu, A. Zhmoginov and L.-C. Chen, "
        "“MobileNetV2: Inverted Residuals and Linear Bottlenecks,” "
        "IEEE CVPR, 2018.",
        "L. Breiman, “Random Forests,” Machine Learning, 45(1), "
        "pp. 5–32, 2001.",
        "C. Cortes and V. Vapnik, “Support-Vector Networks,” Machine "
        "Learning, 20(3), pp. 273–297, 1995.",
        "T. Ojala, M. Pietikäinen and T. Mäenpää, “Multiresolution "
        "gray-scale and rotation invariant texture classification with local "
        "binary patterns,” IEEE TPAMI, 24(7), 2002.",
        "F. Pedregosa et al., “Scikit-learn: Machine Learning in "
        "Python,” J. Machine Learning Research, 12, pp. 2825–2830, 2011.",
        "M. Abadi et al., “TensorFlow: Large-Scale Machine Learning on "
        "Heterogeneous Systems,” 2015, https://www.tensorflow.org.",
        "G. Bradski, “The OpenCV Library,” Dr. Dobb's Journal of "
        "Software Tools, 2000.",
        "JaidedAI, “EasyOCR: Ready-to-use OCR,” "
        "https://github.com/JaidedAI/EasyOCR.",
        "S. Ramírez, “FastAPI,” https://fastapi.tiangolo.com; "
        "Vercel, “Next.js,” https://nextjs.org.",
    ]
    counter = 1

    def emit(items):
        nonlocal counter
        for ref in items:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            p.paragraph_format.space_after = Pt(8)
            p.add_run(f"[{counter}] {ref}")
            counter += 1

    h2(doc, "Literature on Fake-Currency Detection")
    emit(lit_refs)
    h2(doc, "Idea Sources and Datasets Used")
    emit(idea_data_refs)
    h2(doc, "Methods, Libraries and Tools")
    emit(method_tool_refs)


# ===========================================================================
# build
# ===========================================================================

def build():
    figs = {
        "workflow": GEN / "workflow.png",
        "arch": GEN / "architecture.png",
        "dfd": GEN / "dfd.png",
        "activity": GEN / "activity.png",
        "cnn": GEN / "cnn.png",
        "rf": GEN / "random_forest.png",
        "bar": GEN / "barchart.png",
        "roc": GEN / "roc.png",
        "confusion": GEN / "confusion.png",
        "usecase": GEN / "usecase.png",
        "sequence": GEN / "sequence.png",
        "guilloche1": GEN / "guilloche_2026.png",
        "guilloche2": GEN / "guilloche_2029.png",
    }
    try:
        fig_vflow(figs["workflow"], [
            ("Input", ["Banknote photo (upload / camera)"]),
            ("Pre-processing", ["Locate & crop note", "Denoise, grayscale, "
                                "resize", "Feature scaling"]),
            ("Machine Learning Models", ["MobileNetV2 (CNN)", "SVM, Random "
                                         "Forest, KNN, Logistic Regression"]),
            ("Forensic Checks (visible-light)", ["Serial, denomination, "
                                                 "watermark, thread, colour, ..."]),
            ("Fusion + Hard Gates", ["0.4 x CNN + 0.6 x forensic", "structure / "
                                     "colour / size veto"]),
            ("Verdict", ["REAL / SUSPICIOUS / FAKE / UNVERIFIED"]),
            ("Evaluation", ["Accuracy, Precision, Recall", "F1 / macro-F1, "
                            "Confusion matrix"]),
        ])
        fig_architecture(figs["arch"])
        fig_vflow(figs["dfd"], [
            ("User", ["Provides banknote photo"]),
            ("Capture / Upload", ["Image acquired by the system"]),
            ("Locate & Pre-process", ["Crop note, denoise, resize, scale"]),
            ("Extract Features", ["50-d vector + forensic measurements"]),
            ("Classify & Check", ["CNN + classical ML + forensic checks"]),
            ("Fuse & Gate", ["Combine scores, apply hard gates"]),
            ("Output Verdict", ["REAL / SUSPICIOUS / FAKE / UNVERIFIED to user"]),
        ], header_color=C_BLUE)
        fig_vflow(figs["activity"], [
            ("Capture / Upload note", []),
            ("Locate & pre-process", []),
            ("Extract features + forensic checks", []),
            ("Run ML models", []),
            ("Fuse + apply gates", []),
            ("Show verdict", []),
        ], start_end=True)
        fig_cnn(figs["cnn"])
        fig_random_forest(figs["rf"])
        fig_barchart(figs["bar"])
        fig_roc(figs["roc"])
        fig_confusion(figs["confusion"])
        fig_usecase(figs["usecase"])
        fig_sequence(figs["sequence"])
        make_guilloche("ABHI-500-2026", figs["guilloche1"])
        make_guilloche("ABHI-500-2029", figs["guilloche2"])
    except Exception as exc:
        print(f"(diagram generation issue: {exc})")

    doc = Document()
    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(12)
    normal.paragraph_format.line_spacing = 1.5

    for name, size in [("Heading 1", 17), ("Heading 2", 14), ("Heading 3", 12.5)]:
        st = doc.styles[name]
        st.font.name = "Times New Roman"
        st.font.size = Pt(size)
        st.font.color.rgb = HEADING
        st.font.bold = True

    secA = doc.sections[0]
    secA.top_margin = Inches(1)
    secA.bottom_margin = Inches(1)
    secA.left_margin = Inches(1.25)
    secA.right_margin = Inches(1)
    cover(doc)

    doc.add_section(WD_SECTION.NEW_PAGE)
    secB = doc.sections[-1]
    set_pgnum(secB, "lowerRoman", 1)
    footer_pagenum(secB)
    certificate(doc)
    declaration(doc)
    dedication(doc)
    abstract(doc)
    contents(doc)

    doc.add_section(WD_SECTION.NEW_PAGE)
    secC = doc.sections[-1]
    set_pgnum(secC, "decimal", 1)
    footer_pagenum(secC)

    lit = chapters(doc, figs)
    appendices(doc)
    references(doc, lit)

    DOCS.mkdir(parents=True, exist_ok=True)
    doc.save(OUT)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    build()
