"""
Phase F.2 — verdict-threshold calibration.

The fused verdict uses combined_score = 0.4*CNN + 0.6*forensic with hand-set
cutoffs (REAL >= 0.65, FAKE < 0.35). This script replaces "we guessed 0.65/0.35"
with evidence: it runs the REAL /predict pipeline over the labelled corpus,
collects each note's combined_score, and computes the ROC curve + the
Youden's-J optimal single threshold, plus how the current cutoffs perform.

It writes docs/CALIBRATION.md. It does NOT silently change the production
thresholds — threshold changes on a ~65-image corpus are not statistically
safe, so the recommendation is reported honestly and applied only if it clearly
dominates. (This is the documented, evidence-based version of the Phase F.2
acceptance criterion: "thresholds traceable to a curve".)

Run:
    venv\\Scripts\\python.exe scripts\\calibrate_thresholds.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

# Windows consoles default to cp1252 and choke on the → / ₹ glyphs we print.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

INDEX = os.path.join(ROOT, "dataset", "index.json")
OUT = os.path.join(ROOT, "docs", "CALIBRATION.md")

# Current production cutoffs (backend/main.py).
REAL_CUT = 0.65
FAKE_CUT = 0.35


def _collect():
    from fastapi.testclient import TestClient
    from backend.main import app

    client = TestClient(app)
    with open(INDEX, "r", encoding="utf-8") as fh:
        samples = json.load(fh)["samples"]

    rows = []  # (label_is_genuine, combined_score, verdict)
    print(f"Scoring {len(samples)} images through /predict ...")
    for i, s in enumerate(samples, 1):
        path = os.path.join(ROOT, s["path"].replace("/", os.sep))
        try:
            with open(path, "rb") as fh:
                data = fh.read()
            body = client.post(
                "/predict",
                files={"file": (os.path.basename(path), data, "image/jpeg")},
            ).json()
            cnn = float(body.get("raw_prediction", 0.0))
            forensic = float(body.get("forensic_score", 0.0)) / 100.0
            combined = 0.4 * cnn + 0.6 * forensic
            rows.append((s["label"] == "genuine", combined, body.get("prediction")))
        except Exception as exc:
            print(f"  skip {s['path']}: {exc}")
        if i % 10 == 0:
            print(f"  ...{i}/{len(samples)}")
    return rows


def main():
    import numpy as np
    from sklearn.metrics import roc_auc_score, roc_curve

    rows = _collect()
    if not rows:
        print("No scored rows — is dataset/index.json present?")
        return 1

    y = np.array([1 if g else 0 for g, _, _ in rows])      # 1 = genuine
    scores = np.array([c for _, c, _ in rows])
    n_gen = int(y.sum())
    n_fake = int((1 - y).sum())

    if n_gen == 0 or n_fake == 0:
        print("Need both genuine and fake samples to calibrate.")
        return 1

    # ---- verdict confusion matrix (doubles as the no-regression check) ----
    verdicts = ("REAL", "SUSPICIOUS", "FAKE", "UNVERIFIED")
    confusion = {"genuine": {v: 0 for v in verdicts},
                 "fake": {v: 0 for v in verdicts}}
    for is_gen, _, verdict in rows:
        bucket = "genuine" if is_gen else "fake"
        if verdict in confusion[bucket]:
            confusion[bucket][verdict] += 1
    print("\n=== End-to-end verdict confusion (rows = ground truth) ===")
    print(f"{'':9}| {'REAL':>6} {'SUSP':>6} {'FAKE':>6} {'UNVER':>6}")
    for gt in ("genuine", "fake"):
        c = confusion[gt]
        print(f"{gt:9}| {c['REAL']:>6} {c['SUSPICIOUS']:>6} {c['FAKE']:>6} {c['UNVERIFIED']:>6}")
    gen_fp = confusion["genuine"]["FAKE"]
    fake_fn = confusion["fake"]["REAL"]
    print(f"false positives (genuine→FAKE): {gen_fp}/{n_gen}   "
          f"false negatives (fake→REAL): {fake_fn}/{n_fake}")

    auc = roc_auc_score(y, scores)
    fpr, tpr, thr = roc_curve(y, scores)
    youden = tpr - fpr
    best_i = int(np.argmax(youden))
    best_thr = float(thr[best_i])

    # How the current single boundary (midpoint of the SUSPICIOUS band) and the
    # production two-cutoff scheme behave.
    def confusion_at(t):
        pred_gen = scores >= t
        tp = int(((pred_gen) & (y == 1)).sum())
        fp = int(((pred_gen) & (y == 0)).sum())
        tn = int(((~pred_gen) & (y == 0)).sum())
        fn = int(((~pred_gen) & (y == 1)).sum())
        return tp, fp, tn, fn

    tp, fp, tn, fn = confusion_at(best_thr)

    lines = []
    lines.append("# Verdict-threshold calibration (Phase F.2)\n")
    lines.append("_Auto-generated by `scripts/calibrate_thresholds.py` — do not hand-edit._\n")
    lines.append(f"- Corpus: **{len(rows)} images** ({n_gen} genuine / {n_fake} fake)")
    lines.append(f"- Score: `combined = 0.4·CNN + 0.6·forensic`")
    lines.append(f"- **ROC-AUC = {auc:.3f}** (1.0 = perfect, 0.5 = chance)\n")
    lines.append("## Youden's-J optimal single threshold\n")
    lines.append(f"- Optimal genuine/fake boundary: **{best_thr:.3f}**")
    lines.append(f"- At that threshold: TP={tp} FP={fp} TN={tn} FN={fn}")
    lines.append(f"  (genuine kept {tp}/{n_gen}, fakes caught {tn}/{n_fake})\n")
    lines.append("## Current production cutoffs\n")
    lines.append(f"- REAL when combined ≥ **{REAL_CUT}**, FAKE when combined < **{FAKE_CUT}**, "
                 f"else SUSPICIOUS (plus structural/colour/proportion hard gates and the "
                 f"Phase-K readability gate).")
    lines.append(f"- The optimal single boundary ({best_thr:.3f}) sits "
                 f"{'inside' if FAKE_CUT <= best_thr <= REAL_CUT else 'outside'} the current "
                 f"SUSPICIOUS band [{FAKE_CUT}, {REAL_CUT}].\n")
    lines.append("## Honest recommendation\n")
    if FAKE_CUT <= best_thr <= REAL_CUT:
        lines.append(
            "The data-optimal boundary falls **within** the current SUSPICIOUS band, "
            "so the hand-set 0.65 / 0.35 cutoffs are consistent with the evidence: "
            "scores in between are correctly treated as 'verify by hand' rather than "
            "forced to REAL or FAKE. **No change applied.**")
    else:
        lines.append(
            f"The data-optimal boundary ({best_thr:.3f}) lies outside the current band, "
            "suggesting the cutoffs could shift — but on a ~65-image corpus this is not "
            "statistically safe to apply blindly. **Recorded, not auto-applied;** revisit "
            "once the dataset grows.")
    lines.append(
        "\n> Caveat: with this corpus size the ROC is coarse (few points). This is an "
        "evidence trail, not a production calibration — the dominant lever remains more "
        "data, especially real physical counterfeits.")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print("\n".join(lines))
    print(f"\nWrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
